### ISSUE TITLE
auto_vot_performance.py broken

### ISSUE THREAD

**Issue by NoahRichardNelson** [mlml/autovot#88]
In attempting to run 'auto_vot_performance.py' (using Python 3.6.5 on Mac OSX 10.11.6) I ran into the following issues:
 - NameError: name 'TextGrid' is not defined
     - fixed by changing line 59 to >> textgrid = tg.TextGrid()
 - NameError: name 're' is not defined
     - fixed by importing re
 - TypeError: addInterval() missing 1 required positional argument: 'interval'
     - did not attempt to fix this one

If I attempt to run it using Python 2.7.10 I instead get an import error for the module 'builtins'.

Additional notes regarding the README:
 - example uses the flag --csvF but the version of auto_vot_performance.py that I have wants the flag --csv_file

**Comment by MichaelGoodale** [comment]
Hi Noah, thanks again for the bug reporting, it's super helpful! 

I updated the script to hopefully fix these issue(also caught another in the process too), but I couldn't seem to run into your third bug about addInterval() while I was fixing it. Please let me know if the updated script has the issue still and I'll try and fix it.

The builtins import error should be fixed by `pip install future` (one of the packages in the requirements.txt).

Thanks!

**Comment by NoahRichardNelson** [comment]
I think it's fixed, thanks! I can't seem to reproduce the interval error either.
