### ISSUE TITLE
How to handle prevoicing?

### ISSUE THREAD

**Issue by FredrikKarlssonSpeech** [mlml/autovot#91]
Hi,

Great work. An automatic VOT analysis machine would be a great advancement for Praat users out there. 
However, since the output (and expected input) is always an interval, is prevoicing (very common across languages, and in dysarthria) handled? I see a "neg" marker, which I assume would be the way to mark prevoicing, but I cannot seem to get one marked using the classifier.

Thanks!

Fredrik

**Comment by thealk** [comment]
I know this comment was resolved over email, but I am adding a comment and closing this issue in order to be of use to other users.

Indeed at this time AutoVOT does not handle negative VOT/prevoicing. For these cases, it is best to use the [Dr.VOT system](https://github.com/MLSpeech/Dr.VOT). This caveat has also been added to the AutoVOT README.

Thanks for this comment!
